services:
  fiap-pos-tech-api-db:
    image: postgres:15-alpine
    container_name: fiap-pos-tech-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-fiap_pos_tech_db}
      POSTGRES_USER: ${DB_USER:-fiap_pos_tech_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fiap_pos_tech_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_api_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-fiap_pos_tech_user}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-network

  fiap-pos-tech-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fiap-pos-tech-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: ${DEV_PORT:-3001}
      DATABASE_URL: postgresql://${DB_USER:-fiap_pos_tech_user}:${DB_PASSWORD:-fiap_pos_tech_password}@fiap-pos-tech-api-db:5432/${DB_NAME:-fiap_pos_tech_db}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET:-your_webhook_secret_key}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://fiap-keycloak:8080}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-fiap-pos-tech}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-pos-tech-api}
    ports:
      - "${DEV_PORT:-3001}:3001"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    depends_on:
      fiap-pos-tech-api-db:
        condition: service_healthy
    networks:
      - api-network
    profiles:
      - dev

  fiap-pos-tech-api-prd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-pos-tech-api-prd
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PRD_PORT:-3002}
      DATABASE_URL: postgresql://${DB_USER:-fiap_pos_tech_user}:${DB_PASSWORD:-fiap_pos_tech_password}@fiap-pos-tech-api-db:5432/${DB_NAME:-fiap_pos_tech_db}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET:-your_webhook_secret_key}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://fiap-keycloak:8080}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-fiap-pos-tech}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-pos-tech-api}
    ports:
      - "${PRD_PORT:-3002}:3002"
    depends_on:
      fiap-pos-tech-api-db:
        condition: service_healthy
    networks:
      - api-network
    profiles:
      - prd

volumes:
  postgres_api_data:
    driver: local

networks:
  api-network:
    external: true
    name: fiap-pos-tech-network
