apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-pos-tech-config
  namespace: fiap-pos-tech
data:
  PORT: "3001"
  NODE_ENV: "production"
  POSTGRES_DB: "fiap_pos_tech_db"
  POSTGRES_USER: "fiap_pos_tech_user"
  DB_PORT: "5432"
  DATABASE_HOST: "fiap-pos-tech-db-service"